# Generated by Django 4.2.3 on 2023-07-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotlib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
    ]
