# Generated by Django 4.2.3 on 2023-07-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotlib', '0002_alter_library_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='doc',
            new_name='documentation',
        ),
    ]
