# Generated by Django 4.2.3 on 2023-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotlib', '0003_rename_doc_library_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
