# Generated by Django 4.2.3 on 2023-07-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0004_remove_testplan_test_case'),
        ('testspec', '0002_remove_keywordcallargument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_plans',
            field=models.ManyToManyField(to='testplan.testplan'),
        ),
    ]
