# Generated by Django 4.2.3 on 2023-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0004_remove_testplan_test_case'),
        ('testspec', '0003_testcase_test_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_plans',
            field=models.ManyToManyField(blank=True, related_name='test_cases', to='testplan.testplan'),
        ),
    ]
