# Generated by Django 4.2.3 on 2023-08-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testspec', '0005_alter_keywordcall_test_case_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordcall',
            options={'ordering': ['index']},
        ),
    ]
