# Generated by Django 4.2.3 on 2023-07-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testplan', '0004_remove_testplan_test_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('result', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=255)),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplan.testplan')),
            ],
        ),
    ]
