# Generated by Django 4.2.3 on 2023-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotexec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='directory',
        ),
        migrations.AddField(
            model_name='testexecution',
            name='log',
            field=models.CharField(default='Not executed', max_length=255),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='result',
            field=models.CharField(default='Not executed', max_length=255),
        ),
    ]
