# Generated by Django 4.2.3 on 2023-07-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0006_remove_libraryimportargument_import_library_and_more'),
        ('robotexec', '0002_remove_testexecution_directory_testexecution_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='testplan.testplan'),
        ),
    ]
