# Generated by Django 4.2.3 on 2023-07-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='arg1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='arg2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='arg3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='arg4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='arg5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='return_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
