# Generated by Django 4.2.3 on 2023-07-21 14:19

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('robotkw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('return_value', models.CharField(blank=True, max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotkw.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCallOptionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testspec.keywordcall')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCallArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testspec.keywordcall')),
            ],
        ),
        migrations.AddField(
            model_name='keywordcall',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testspec.testcase'),
        ),
    ]
