# Generated by Django 4.2.3 on 2023-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testspec', '0002_testcase_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='documentation',
            field=models.TextField(),
        ),
    ]
