# Generated by Django 4.2.3 on 2023-07-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordcall',
            old_name='keyword',
            new_name='calling_keyword',
        ),
    ]
