# Generated by Django 4.2.3 on 2023-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_rename_keyword_keywordcall_calling_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcallargument',
            name='name',
        ),
    ]
