# Generated by Django 4.2.3 on 2023-07-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('return_value', models.CharField(blank=True, max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.keyword')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(choices=[('Library', 'Library')], default='Library', max_length=255)),
                ('argument', models.CharField(choices=[('Library', [('RoboSAPiens.DE', 'RoboSAPiens'), ('Browser', 'Browser')])], default='Library', max_length=255)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.TextField()),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.testsuite')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SettingOptionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.setting')),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.testsuite'),
        ),
        migrations.CreateModel(
            name='LibraryOptionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.library')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordPositionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordOptionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCallPositionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('value', models.CharField(max_length=255)),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.keywordcall')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='KeywordCallOptionalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.keywordcall')),
            ],
        ),
        migrations.AddField(
            model_name='keywordcall',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.testcase'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.library'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('test_suite', 'name'), name='testcase_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='settingoptionalargument',
            constraint=models.UniqueConstraint(fields=('setting', 'name'), name='setting_optional_argument_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('test_suite', 'name', 'argument'), name='setting_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='keywordcallpositionalargument',
            constraint=models.UniqueConstraint(fields=('keyword_call', 'index'), name='keyword_call_positional_argument_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='keywordcalloptionalargument',
            constraint=models.UniqueConstraint(fields=('keyword_call', 'name'), name='keyword_call_optional_argument_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(fields=('test_case', 'index'), name='keyword_call_primary_key'),
        ),
    ]
