# Generated by Django 4.2.3 on 2023-07-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.testsuite')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_value', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('arg1', models.CharField(max_length=255)),
                ('arg2', models.CharField(max_length=255)),
                ('arg3', models.CharField(max_length=255)),
                ('arg4', models.CharField(max_length=255)),
                ('arg5', models.CharField(max_length=255)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.testcase')),
            ],
        ),
    ]
