# Generated by Django 4.2.3 on 2023-07-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_keywordcall_arg1_keywordcall_arg2_keywordcall_arg3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BuiltIn', 'BuiltIn'), ('RoboSAPiens', 'RoboSAPiens')], default=('BuiltIn', 'BuiltIn'), max_length=255)),
                ('arg1', models.CharField(blank=True, max_length=255)),
                ('arg2', models.CharField(blank=True, max_length=255)),
                ('arg3', models.CharField(blank=True, max_length=255)),
                ('arg4', models.CharField(blank=True, max_length=255)),
                ('arg5', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='keyword',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.library'),
        ),
    ]
