# Generated by Django 4.2.3 on 2023-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_library_alter_keyword_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(choices=[('BuiltIn', 'BuiltIn'), ('RoboSAPiens', 'RoboSAPiens')], default='BuiltIn', max_length=255),
        ),
    ]
