# Generated by Django 4.2.3 on 2023-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_keywordcall_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(fields=('test_case', 'index'), name='unique_keyword_call_per_test_case'),
        ),
    ]
