# Generated by Django 4.2.3 on 2023-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(choices=[('BuiltIn', 'BuiltIn'), ('RoboSAPiens', 'RoboSAPiens')], max_length=255),
        ),
    ]
