# Generated by Django 4.2.3 on 2023-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testspec', '0002_remove_keywordcallargument_name'),
        ('testplan', '0002_rename_testsuite_testplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='test_case',
            field=models.ManyToManyField(to='testspec.testcase'),
        ),
    ]
