# Generated by Django 4.2.3 on 2023-07-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0003_testplan_test_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='test_case',
        ),
    ]
