# Generated by Django 4.2.3 on 2023-07-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0004_remove_testplan_test_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryimport',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_imports', to='testplan.testplan'),
        ),
        migrations.AddConstraint(
            model_name='libraryimport',
            constraint=models.UniqueConstraint(fields=('test_plan', 'library'), name='unique_library_import'),
        ),
    ]
