# Generated by Django 4.2.3 on 2023-07-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0005_alter_libraryimport_test_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryimportargument',
            name='import_library',
        ),
        migrations.AddField(
            model_name='libraryimportargument',
            name='library_import',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='testplan.libraryimport'),
            preserve_default=False,
        ),
    ]
