# Generated by Django 4.2.3 on 2023-07-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0006_remove_libraryimportargument_import_library_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryimportargument',
            old_name='argument',
            new_name='name',
        ),
    ]
