# Generated by Django 4.2.3 on 2023-07-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robotlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotlib.library')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryImportArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('import_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testexec.libraryimport')),
            ],
        ),
        migrations.AddField(
            model_name='libraryimport',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testexec.testsuite'),
        ),
    ]
